### ISSUE TITLE
Workspace Go1CMS not Visible being not Public 

### ISSUE THREAD

**Issue by chechani** [TridotsTech/go1cms#5]
Workspace Go1CMS not Visible being not Pubic

**Comment by satisharalkar** [comment]
@chechani I have installed app on V14 and observed same issue. Module shortcut is not shown. If you got the workaround then please let me know. Thanks

**Comment by nash22t** [comment]
> @chechani I have installed app on V14 and observed same issue. Module shortcut is not shown. If you got the workaround then please let me know. Thanks

i have sim

**Comment by harshsurve** [comment]
I,ve Installed on V14 . Module Shortcut is shown. Install in Dev mode. After installation "bench update" and "bench migrate"
